// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "translationEnabled": boolean;
      "mineruBaseURL": string;
      "mineruApiToken": string;
      "mineruModelVersion": string;
      "mineruLanguage": string;
      "mineruEnableTable": boolean;
      "mineruEnableFormula": boolean;
      "mineruEnableOCR": boolean;
      "mineruPageRanges": string;
      "mineruPollIntervalMs": number;
      "mineruTimeoutSec": number;
      "translationProvider": string;
      "translationBaseURL": string;
      "translationApiKey": string;
      "translationModel": string;
      "translationTargetLanguage": string;
      "translationSystemPrompt": string;
      "translationTemperature": string;
      "translationChunkChars": number;
      "translationConcurrency": number;
      "skipImages": boolean;
      "skipTables": boolean;
      "skipFrontMatter": boolean;
      "skipReferences": boolean;
      "noteHeading": string;
      "includeOriginalMarkdown": boolean;
    };
  }
}
