pref("translationEnabled", true);
pref("mineruBaseURL", "https://mineru.net/api/v4");
pref("mineruApiToken", "");
pref("mineruModelVersion", "vlm");
pref("mineruLanguage", "en");
pref("mineruEnableTable", false);
pref("mineruEnableFormula", false);
pref("mineruEnableOCR", false);
pref("mineruPageRanges", "");
pref("mineruPollIntervalMs", 3000);
pref("mineruTimeoutSec", 300);
pref("translationProvider", "openai");
pref("translationBaseURL", "");
pref("translationApiKey", "");
pref("translationModel", "gpt-4.1-mini");
pref("translationProfileName", "");
pref("translationProfiles", "[]");
pref("translationTargetLanguage", "简体中文");
pref("translationSystemPrompt", "你是一名学术论文翻译助手。请准确翻译为目标语言，保留 Markdown 结构、标题层级、列表、公式、缩写和专业术语；不要添加额外解释。");
pref("translationTemperature", "0.1");
pref("translationChunkChars", 7000);
pref("translationConcurrency", 2);
pref("skipImages", true);
pref("skipTables", true);
pref("skipFrontMatter", true);
pref("skipReferences", true);
pref("noteHeading", "PDF 翻译");
pref("includeOriginalMarkdown", false);
